baseURL = "http://ramiteku.com/"
copyright = "rami Technologies"
languageCode = "en-us"
title = "rami Technologies"
theme = "hermit"
themeColor = "#494f5c"

[languages]
  [languages.en]
    title = "rami Technologies"
    weight = 1
    [languages.en.params]
      linkedin = "https://ramiteku/whoever"
  [languages.jp]
    title = "ラミ テクノロジ"
    weight = 2
    [languages.jp.params]
      linkedin = "https://ramiteku/jp/whoever"
      [languages.jp.params.navigation]

[params]
  [params.navigation]
    help = "Help"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
